### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by thegreatestgiant** [KozmikNano/vscode-server-template#1]
I created a fresh linode on ubuntu 22.04
installed docker.io docker and docker-compose
and ran
git clone https://github.com/kozmiknano/vscode-server-template.git
cd vscode-server-template
coder template create

but it just gave me an error
`Command 'coder' not found, did you mean:
  command 'cover' from deb libdevel-cover-perl (1.36-2build2)
Try: sudo apt install <deb name>`
I also created a docker image and ran it with port 8080 but it didn't work

**Comment by KozmikNano** [comment]
This project is actually built for a price of software called coder, which lets you setup develop environments that you can access on any device with a web browser. I like to think of it more like a better version of GitHub codespaces.

This GitHub repo on particular is a template you can add to setup a fully featured version of vscode, compared to the default code-server. The difference being that this repo allows settings sync, Microsoft extensions for VSCode and more. 


You can find out more info about coder here: [https://coder.com/docs/v2/latest](https://coder.com/docs/v2/latest)

If you don’t mind me asking, would you like to see this separated from coder itself, and for it to just be a docker image?

**Comment by thegreatestgiant** [comment]
I would like for it to be it's own docker image that is easily deployable

I have code-server set up, I understand that this is coder v1, is there a way I could use your template in order to get access to more extensions?

**Comment by KozmikNano** [comment]
Other than upgrading to coder v2, not really. You could just install vscode-server, but that would in your base system and not in a docket container. I will spend time today creating a separate docker image!
