### ISSUE TITLE
Can you briefly explain how you got the settings sync to work?

### ISSUE THREAD

**Issue by GBT55** [KozmikNano/vscode-server-template#2]
I'm trying it on my own coder project. 
So far I've managed to use another marketplace, exporting it as a variable. But how do you get the settings sync to work?

Thank you in advance!

**Comment by KozmikNano** [comment]
Instead of using coder-server, this uses the actual Microsoft version, which has all of the features unlocked. Only reason this is available is because of github codespaces.

**Comment by KozmikNano** [comment]
If you look [here](https://github.com/KozmikNano/vscode-server-template/blob/7f984f8c416780ae0b6659d03936626f02ff453b/main.tf#L36) you can see where it gets installed, and the line below it is to turn it on.

**Comment by GBT55** [comment]
> If you look [here](https://github.com/KozmikNano/vscode-server-template/blob/7f984f8c416780ae0b6659d03936626f02ff453b/main.tf#L36) you can see where it gets installed, and the line below it is to turn it on.

Wait... is this legal? 🤣
