### ISSUE TITLE
VSCode Web grayed out

### ISSUE THREAD

**Issue by hazre** [KozmikNano/vscode-server-template#3]
How would I go about connecting to the web version?

**Comment by hazre** [comment]
when I go to /apps/code-server, I get redirected correctly but all just a white blank page.

**Comment by KozmikNano** [comment]
It will be under a subdomain. Please check the terraform configuration :)

**Comment by hazre** [comment]
Ah I didn't realize. Would be nice if this was noted on the readme

**Comment by KozmikNano** [comment]
> Ah I didn't realize. Would be nice if this was noted on the readme. Thanks anyway

I will definitely add it to the README. Thanks for the recommendation:)
